backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "static/images/original"
site_url: https://nextport-folio.netlify.app

# media_library:
#   name: cloudinary
#   config:
#     cloud_name: "biaksangmunsong"
#     api_key: "899542633858753"
#     default_transformations:
#       - - fetch_format: auto
#           width: 1000
#           quality: auto
#           crop: scale

collections:
  - name: "pages"
    label: "Pages"
    create: false
    editor:
      preview: false
    files:
      - name: "home_page"
        label: "Home page"
        file: "page-data/homePage.json"
        format: "json"
        extension: "json"
        fields:
          - { name: "title", label: "Page title", widget: "string" }
          - { name: "description", label: "Page description", widget: "string" }
          - name: "content"
            label: "Content"
            widget: "object"
            fields:
              - { name: "heading1", label: "Heading 1", widget: "text" }
              - { name: "cover_image", label: "Cover image", widget: "image", allow_multiple: false }
              - { name: "paragraph1", label: "Paragraph 1", widget: "text" }
      
      - name: "about_page"
        label: "About page"
        file: "page-data/aboutPage.md"
        format: "frontmatter"
        extension: "md"
        preview_path: "about"
        fields:
          - name: "title"
            label: "Page title"
            widget: "string"
          - name: "desc"
            label: "Page description"
            widget: "string"
          - name: "body"
            label: "Body"
            widget: "markdown"