backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
site_url: https://nextport-folio.netlify.app

# media_library:
#   name: cloudinary
#   output_filename_only: true
#   config:
#     cloud_name: "biaksangmunsong"
#     api_key: "899542633858753"

media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: "biaksangmunsong"
    api_key: "899542633858753"
    default_transformations:
      - - fetch_format: auto
          width: 1000
          quality: auto
          crop: scale

collections:
  - name: "pages"
    label: "Pages"
    create: false
    files:
      - name: "about_page"
        label: "About page"
        file: "/page-data/aboutPage.md"
        format: "frontmatter"
        extension: "md"
        fields:
          - name: "title"
            label: "Page title"
            widget: "string"
          - name: "desc"
            label: "Page description"
            widget: "string"
          - name: "body"
            label: "Body"
            widget: "markdown"